### ISSUE TITLE
Error when using with separate firebase installation

### ISSUE THREAD

**Issue by kai-oswald** [kai-oswald/nuxt-firebase#1]
Getting "Component auth has not been registered yet" when `firebase` is imported.
This is a known issue (see https://stackoverflow.com/questions/71057826/get-component-auth-has-not-been-registered-yet-when-using-firebase-authenticat)

Running `npx nuxi clean` fixes it for the next build, but it's quite annoying to clean everytime we run `npm run dev`.

I'm not sure how to fix that.

**Comment by ABB65** [comment]
Hi, I have read that this problem is related to some modules (Auth) in Firebase packages using the client browser cache.
in my own project
I tried if(process.client) and got no error.
I think there may be a solution for this for now.

**Comment by kai-oswald** [comment]
This didn't fix it. I don't get it on local only when using the package from npm.
This error doesn't make sense? The `firebase.client.ts` plugin is only called on the client-side.

Could you elaborate a bit further where you would use if(process.client)? @ABB65

**Comment by ABB65** [comment]
> This didn't fix it. I don't get it on local only when using the package from npm. This error doesn't make sense? The `firebase.client.ts` plugin is only called on the client-side.
> 
> Could you elaborate a bit further where you would use if(process.client)? @ABB65

I looked at Stackoverflow when I got the error in my project. This was a bug in Angular project as well. I read in another source that the error can be solved with firebase/lite package and it is related to client side browser cache usage. For this reason, I thought that client side initialization on Nuxt could be a solution. I tried the code below and it worked

```
import { initializeApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'
import { getAuth } from 'firebase/auth'

export const useFirebase = () => {
  const firebaseConfig = {
    // config
  }

  const firebaseApp = initializeApp(firebaseConfig)
  const firestore = getFirestore(firebaseApp)
  let auth = null

  if (process.client) {// I was getting error before this line. I didn't get any errors after this fix.
    auth = getAuth(firebaseApp)
  }

  return {
    firebaseApp,
    firestore,
    auth
  }
}
```

**Comment by kai-oswald** [comment]
Hey @ABB65. Thanks for elaborating.
I just tested this on v0.3.1-next, but unfortunately it doesn't work and I'm getting the same error.

I also only get this error when I install the package via npm and cannot reproduce it locally in the playground. 
So maybe there's something wrong with plugin registration.

Full error:
```
500
Component auth has not been registered yet

at Provider.initialize (http://localhost:3000/_nuxt/node_modules/@firebase/component/dist/esm/index.esm2017.js?v=50314b63:232:19)
at initializeAuth (http://localhost:3000/_nuxt/node_modules/.vite/deps/@firebase_auth.js?v=50314b63:359:25)
at getAuth (http://localhost:3000/_nuxt/node_modules/.vite/deps/@firebase_auth.js?v=50314b63:5105:16)
at http://localhost:3000/_nuxt/node_modules/@oswld/nuxt-firebase/dist/runtime/plugins/firebase.client.mjs?v=50314b63:12:12
at fn (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=50314b63:138:27)
at callWithNuxt (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=50314b63:143:12)
at applyPlugin (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=50314b63:89:29)
at applyPlugins (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=50314b63:98:11)
at async initApp (http://localhost:3000/_nuxt/D:/dev/nuxt-firebase/demo/node_modules/nuxt/dist/app/entry.mjs:41:7)
```
